/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareRouteImport } from './routes/share'
import { Route as ClientIdRouteImport } from './routes/client.$id'
import { Route as ApiPublicShareRouteImport } from './routes/api/public/share'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareRoute = ShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientIdRoute = ClientIdRouteImport.update({
  id: '/client/$id',
  path: '/client/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShareRoute = ApiPublicShareRouteImport.update({
  id: '/api/public/share',
  path: '/api/public/share',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/share': typeof ShareRoute
  '/client/$id': typeof ClientIdRoute
  '/api/public/share': typeof ApiPublicShareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/share': typeof ShareRoute
  '/client/$id': typeof ClientIdRoute
  '/api/public/share': typeof ApiPublicShareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/share': typeof ShareRoute
  '/client/$id': typeof ClientIdRoute
  '/api/public/share': typeof ApiPublicShareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/share' | '/client/$id' | '/api/public/share'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/share' | '/client/$id' | '/api/public/share'
  id: '__root__' | '/' | '/share' | '/client/$id' | '/api/public/share'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShareRoute: typeof ShareRoute
  ClientIdRoute: typeof ClientIdRoute
  ApiPublicShareRoute: typeof ApiPublicShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share': {
      id: '/share'
      path: '/share'
      fullPath: '/share'
      preLoaderRoute: typeof ShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/$id': {
      id: '/client/$id'
      path: '/client/$id'
      fullPath: '/client/$id'
      preLoaderRoute: typeof ClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/share': {
      id: '/api/public/share'
      path: '/api/public/share'
      fullPath: '/api/public/share'
      preLoaderRoute: typeof ApiPublicShareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShareRoute: ShareRoute,
  ClientIdRoute: ClientIdRoute,
  ApiPublicShareRoute: ApiPublicShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
